export const MOCK_PRODUCTS = [
    {
        id: 1,
        name: 'Engine Oil Filter',
        category: 'Engine Parts',
        price: 2400,
        image: '🔧',
        rating: 4.8,
        stock: 45,
        description: 'Genuine Toyota engine oil filter for optimal engine protection',
        specifications: 'Compatible with most Toyota models',
    },
    {
        id: 2,
        name: 'Air Filter Assembly',
        category: 'Engine Parts',
        price: 1800,
        image: '🌬️',
        rating: 4.6,
        stock: 32,
        description: 'Original Toyota air filter assembly',
        specifications: 'Standard size, OEM quality',
    },
    {
        id: 3,
        name: 'Brake Pads Set',
        category: 'Suspension',
        price: 5500,
        image: '🛑',
        rating: 4.9,
        stock: 28,
        description: 'Premium brake pad set with superior stopping power',
        specifications: 'Front or rear, comes with shims',
    },
    {
        id: 4,
        name: 'Shock Absorber',
        category: 'Suspension',
        price: 8900,
        image: '🏎️',
        rating: 4.7,
        stock: 15,
        description: 'Genuine Toyota suspension shock absorber',
        specifications: 'Gas-filled, lifetime tested',
    },
    {
        id: 5,
        name: 'Headlight Assembly',
        category: 'Electrical',
        price: 12500,
        image: '💡',
        rating: 4.8,
        stock: 18,
        description: 'LED headlight unit with modern technology',
        specifications: 'Brightness: 5000K, 1000 lumens',
    },
    {
        id: 6,
        name: 'Car Seat Cover',
        category: 'Interior',
        price: 3200,
        image: '🪑',
        rating: 4.5,
        stock: 50,
        description: 'Premium seat cover set for complete protection',
        specifications: 'Universal fit, waterproof material',
    },
    {
        id: 7,
        name: 'Steering Wheel Cover',
        category: 'Interior',
        price: 1500,
        image: '🎡',
        rating: 4.6,
        stock: 35,
        description: 'Leather steering wheel cover for enhanced grip',
        specifications: 'Premium genuine leather, ergonomic design',
    },
    {
        id: 8,
        name: 'Floor Mats',
        category: 'Interior',
        price: 2800,
        image: '🟫',
        rating: 4.4,
        stock: 40,
        description: 'Custom-fit floor mats for your vehicle',
        specifications: 'Durable rubber, easy to clean',
    },
    {
        id: 9,
        name: 'Battery 60Ah',
        category: 'Electrical',
        price: 15800,
        image: '🔋',
        rating: 4.8,
        stock: 12,
        description: 'High-capacity car battery with excellent reliability',
        specifications: 'Cold Cranking Amp: 600, 3 year warranty',
    },
    {
        id: 10,
        name: 'Alternator',
        category: 'Electrical',
        price: 9200,
        image: '⚡',
        rating: 4.7,
        stock: 8,
        description: 'Original Toyota alternator for consistent power',
        specifications: 'Output: 120A, brushless design',
    },
    {
        id: 11,
        name: 'Radiator',
        category: 'Engine Parts',
        price: 11500,
        image: '❄️',
        rating: 4.6,
        stock: 10,
        description: 'Cooling radiator assembly with improved heat dissipation',
        specifications: '3 rows core, aluminum construction',
    },
    {
        id: 12,
        name: 'Spark Plugs (4pcs)',
        category: 'Engine Parts',
        price: 3500,
        image: '✨',
        rating: 4.9,
        stock: 55,
        description: 'Set of 4 premium spark plugs for smooth ignition',
        specifications: 'Gap: 0.028-0.032 inch, Iridium tipped',
    },
    {
        id: 13,
        name: 'Water Pump',
        category: 'Engine Parts',
        price: 6800,
        image: '💧',
        rating: 4.7,
        stock: 14,
        description: 'Genuine Toyota water pump assembly',
        specifications: 'Cast iron body, OEM quality',
    },
    {
        id: 14,
        name: 'Timing Belt',
        category: 'Engine Parts',
        price: 4200,
        image: '⏱️',
        rating: 4.8,
        stock: 20,
        description: 'Precision timing belt for accurate engine timing',
        specifications: 'Teeth count varies, check compatibility',
    },
    {
        id: 15,
        name: 'Suspension Springs',
        category: 'Suspension',
        price: 7500,
        image: '🔀',
        rating: 4.6,
        stock: 16,
        description: 'Heavy-duty suspension springs for improved handling',
        specifications: 'Load capacity: 1500kg per pair',
    },
    {
        id: 16,
        name: 'Windshield Wipers',
        category: 'Electrical',
        price: 1200,
        image: '🧹',
        rating: 4.5,
        stock: 60,
        description: 'Premium windshield wiper blades for clear vision',
        specifications: '24" and 18" set, all-weather',
    },
    {
        id: 17,
        name: 'Dashboard Mat',
        category: 'Interior',
        price: 2200,
        image: '📊',
        rating: 4.3,
        stock: 35,
        description: 'Non-slip dashboard protective mat',
        specifications: 'Soft fabric, UV resistant',
    },
    {
        id: 18,
        name: 'Door Handle Cover',
        category: 'Interior',
        price: 900,
        image: '🚪',
        rating: 4.4,
        stock: 48,
        description: 'Chrome door handle protective cover',
        specifications: 'Easy installation, corrosion resistant',
    },
    {
        id: 19,
        name: 'Fuel Filter',
        category: 'Engine Parts',
        price: 2100,
        image: '⛽',
        rating: 4.7,
        stock: 38,
        description: 'High-efficiency fuel filter for clean combustion',
        specifications: 'Micron: 100, spin-on type',
    },
    {
        id: 20,
        name: 'Air Conditioning Filter',
        category: 'Electrical',
        price: 1600,
        image: '❄️',
        rating: 4.6,
        stock: 42,
        description: 'Cabin air conditioning filter for fresh air',
        specifications: 'Particulate and odor removal',
    },
];

export const CATEGORIES = [
    'All',
    'Engine Parts',
    'Suspension',
    'Electrical',
    'Interior',
];

export const TESTIMONIALS = [
    {
        id: 1,
        name: 'Ravi Kumar',
        text: 'Best quality parts at competitive prices. Highly recommended for anyone looking for genuine Toyota parts!',
        rating: 5,
    },
    {
        id: 2,
        name: 'Priya Sharma',
        text: 'Fast delivery and excellent customer service. Will order again!',
        rating: 5,
    },
    {
        id: 3,
        name: 'Anil Perera',
        text: 'Genuine Toyota parts with warranty. Trust this shop!',
        rating: 5,
    },
];

export const FEATURES = [
    { icon: '✅', title: '100% Authentic', desc: 'Genuine Toyota parts only' },
    { icon: '⚡', title: 'Fast Delivery', desc: 'Same-day delivery in Colombo' },
    { icon: '🛡️', title: 'Full Warranty', desc: 'Extended warranty on all parts' },
    { icon: '💬', title: 'Expert Support', desc: '24/7 customer assistance' },
    { icon: '💳', title: 'Easy Payment', desc: 'Multiple payment options' },
    { icon: '🚚', title: 'Free Shipping', desc: 'On orders above Rs. 5000' },
];